<a href="https://colab.research.google.com/github/RichardAlexandrino/physics/blob/main/Fisica_Modulo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## A versão em uso do Python

In [ ]:
!python --version

Python 3.10.11


# Tipos de Dados

## Numericos

### Inteiros: 'int'

In [ ]:
x = 10
print ("x =", x)
print(type(x))

x = 10
<class 'int'>


In [ ]:
y = int(20)
print('y =', y)
print(type(y))

y = 20
<class 'int'>


In [ ]:
# 1h20

### Decimais: 'float'

In [ ]:
# m eh a massa da particula
m = 80.30 # [m]=kg
print(m)
print(type(m))

80.3
<class 'float'>


In [ ]:
# massa terra - notacao cientifica
massa_t = 5.972e24 # [m]=kg
print(massa_t)
print(type(massa_t))

5.972e+24
<class 'float'>


### Complexos: 'complex'

In [ ]:
z = 9+8j
print(z)
print(type(z))

(9+8j)
<class 'complex'>


## Sequencias

Os elementos são guardados de forma ordenada

### String: 'str'

In [ ]:
my_str = 'Python'
print(my_str)
print(type(my_str))
print(my_str[1])
print(my_str[4])

Python
<class 'str'>
y
o


### Lista: 'list'

In [ ]:
my_list = ['banana', 'abacate', 'laranja', 'pera']
print(my_list)
print(type(my_list))
print(my_list[2])
print(my_list[-2])
print(my_list[:]) # mostrar todos os itens
print(my_list[0:2])
print(my_list[1:3])
print(my_list[::2]) # pula de dois em dois

# lista permite mudança

my_list[0] = 'uva'
print(my_list)

['banana', 'abacate', 'laranja', 'pera']
<class 'list'>
laranja
laranja
['banana', 'abacate', 'laranja', 'pera']
['banana', 'abacate']
['abacate', 'laranja']
['banana', 'laranja']
['uva', 'abacate', 'laranja', 'pera']


### Tuple: 'tuple'

In [ ]:
my_tuple = (11, 25, 78, 43.9)
print(my_tuple)
print(type(my_tuple))

# Tuple nao permite alterar os dados
# my_tuple[2] = 5

(11, 25, 78, 43.9)
<class 'tuple'>


## Conjunto: 'set'

Os elementos **não** são guardados de forma ordenada

In [ ]:
my_set = {100, 40, 'uva'}
print(my_set)
print(type(my_set))

{40, 100, 'uva'}
<class 'set'>


## Dicionario: 'dict'

Linka a chave com o valor

In [ ]:
my_dict = {'nome':'maria','idade':25,'fone':99999999}
print(my_dict)
print(type(my_dict))
print(my_dict['nome'])

{'nome': 'maria', 'idade': 25, 'fone': 99999999}
<class 'dict'>
maria


In [ ]:
tabela = {"tempo":[0,1,2],"posicao":[1.3,5.8,10.0]}
print(tabela)
print(tabela["tempo"])

{'tempo': [0, 1, 2], 'posicao': [1.3, 5.8, 10.0]}
[0, 1, 2]


## Boleano: 'bool'

In [ ]:
var1, var2 = True, False
print(var1, var2)
print(type(var1), type(var2))

True False
<class 'bool'> <class 'bool'>


# Operadores

## Aritimeticos

In [ ]:
x = 5
y = 2
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y) # Mostra a parte inteira da divisão
print(x % y)
print(x ** y) # Exponenciacao

7
3
10
2.5
2
1
25


## Logicos

In [ ]:
t, f = True, False
print(t, f)
print(type(t))

True False
<class 'bool'>


In [ ]:
print(t and f) # E
print(f and f)
print(t and t)
print(not f) # NAO
print(not t)
print(t or f) # OU
print(t != f) # XOR (OU exclusivo)
print(f != f)
print(t != t)

False
False
True
True
False
True
True
False
False


## Relacionais

In [ ]:
x = 10
y = 7
z = 3

print(x > y)
print(x > y > z)
print(x < y)
print(y < x)
print(x == y)
print(x == 10)
print(x == 11)
print(x != y)
print(y != 5)
print(x >= y)
print(z <= x)

True
True
False
True
False
True
False
True
True
True
True


## Atribuicao

In [ ]:
a = 7
b = 2
print(a, b)

a += b
print(a, b)

7 2
9 2


In [ ]:
a -= (a+b)
print(a, b)

a /= b
print(a, b)

a *= b
print(a, b)

-2.0 2
-1.0 2
-2.0 2


# Estruturas de Controle

## Se: "if"

In [ ]:
n = 10

if n > 11:
  print(n * 2) # Precisar identar pra fazer parte do laco
print(n * 3) # Esta fora do laco

30


## Se-se não: "if-else"

In [1]:
number = 10
if number > 11:
  print('é maior que 11')
else:
  print('é menor que 11')

é menor que 11


## Para: "for"

Usado para trabalhar com listas

In [2]:
for i in [1, 2, 3, 4]:
  print(i)

1
2
3
4


In [4]:
my_list = [1, 2, 3, 4, 'banana', 'pera', 'uva']
for i in my_list:
  print(i)

1
2
3
4
banana
pera
uva


In [5]:
my_tuple = (1, 2, 3, 4)
for i in my_tuple:
  print(i)

1
2
3
4


# Importando Bibliotecas

## 'Math' e 'Numpy'

In [9]:
# sqrt(2) - erro!!: a palavra não existe em python, só em sua biblioteca

In [10]:
# import math
# sqrt(2) - erro!!: tem que chamar o 'math' antes sempre

In [15]:
import math
print(math.sqrt(2))
print(math.factorial(3))

1.4142135623730951
6


In [23]:
# Podemos importar a operação para não precisar chamar o math toda hora
from math import sqrt, factorial
print(sqrt(2)) # é necessário chamar o print, senão aparecerá apenas o último comando
factorial(5)

1.4142135623730951


120

In [26]:
import numpy as np

# criando um array de dim 1
A = np.array([1, 2, 3, 4])
print(A)
print(type(A))

[1 2 3 4]
<class 'numpy.ndarray'>


In [27]:
# Alguns atributos do Array A
print(A.ndim) # a dimensao de A
print(A.shape) # as dimensoes do array
print(A.size) # numero de elementos de A
print(A.dtype) # tipo numerico dos elementos

1
(4,)
4
int64


In [33]:
# Acessando os elementos
print(A[0])
print(A[1])
print(A)

1
2
[1 2 3 4]


In [44]:
# Criando um array de dim 2 (chamado matriz na algebra linear)
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(B)
print(type(B))
print(B.shape)
print(B[0])
print(B[2][2]) # (3,3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
[1 2 3]
9


## Funcoes uteis no Numpy

In [73]:
A = np.zeros((4, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
B = np.ones((4, 4))
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
C = np.empty((3, 3))
C # residuos que estão na memoria, nao eh necessario se preocupar

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [71]:
D = np.identity(4)
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

1:55:00